### ISSUE TITLE
ta lib unable to import

### ISSUE THREAD

**Issue by adnls** [mrjbq7/ta-lib#168]
Hi! I saw lot of people have this issue ... my installation is complete (with lot of pointer type warnings) but i can't import the package.
The package has been well added to site-packages i don't understand i tried to set the pass like suggested in issue #6. it didn't worked for me i'm actually working on debian 9 and python 3.6.2 
(64 version).
Please help me!!

**Comment by adnls** [comment]
please

**Comment by adnls** [comment]
i get a strange error -> no module named "talib._ta_lib".
it don't try to import takib but talib._ta_lib. Is it normal?

**Comment by mrjbq7** [comment]
I'm sorry you're having problems.

It's hard to help with such little information.  Typically the only installation problems that we get are Windows 64-bit because the underlying TA-Lib C library is only provided by its author (not me) in a 32-bit binary for Windows, with the source code provided to build it yourself which is a little more difficult on Windows than Linux.

Anyway.

On linux, it should be pretty simple to install the underlying TA-Lib C library by doing the typical configure, make, make install steps as mentioned in the ``README``.  This python wrapper looks for it in some typical known locations:

```python
        include_dirs = [
            '/usr/include',
            '/usr/local/include',
            '/opt/include',
            '/opt/local/include',
        ]

        lib_talib_dirs = [
            '/usr/lib',
            '/usr/local/lib',
            '/usr/lib64',
            '/usr/local/lib64',
            '/opt/lib',
            '/opt/local/lib',
        ]
```

If you are able to start importing ``talib`` but not ``talib._ta_lib`` that often means the module that builds against the underlying TA-Lib C library had some kind of compilation error when you tried to run ``pip install ta-lib`` or ``python setup.py install``.  Usually that error is the last couple warning/error lines outputted (not the incompatible point types warnings we get from cython, more likely unable to find a symbol like TA_RetCode which is defined in the TA-Lib C header files).

If this doesn't help you resolve it, feel free to paste some of your warning/error output when you try and build this ta-lib python wrapper and I'll try and help more.

**Comment by adnls** [comment]
Thanks for help and for the work you've done with this amazing lib!  it's so fast! can't believe it! don't have to reinvent the wheel with a month of C programming and wrapping, you saved my christmas hollydays!.

I would like to show how i managed to install it for those who are using python3.6.2 and maybe other cloth version of python on linux (i tried to install it on a debian VM, on an ubuntu and finally in a debian docker container ; always the same issue... so i deduce that it was a python version issue).

Indeed! don't try to ./configure with prefix=/user ... it doesn't work, just execute ./configure and make and make install. this is not finished!!! You must in addition of that export the path where is located your ta-lib folder containing the  ta_lib.so.0 file or lib_ta.so.0 .. don't remember.

Thank's again!

**Comment by mrjbq7** [comment]
If you ``./configure --prefix=/user`` as you indicated (instead of ``/usr``), then it won't work because thats not a path that I look for by default.  You can always specify a non-traditional path using ``TA_INCLUDE_PATH`` and ``TA_LIBRARY_PATH`` environment variables when running ``setup.py``.

**Comment by adnls** [comment]
Thanks for your explainations, i realize that i made it work but i didn't know exactly why.
hank you again for your work and the time you took for answering me.

I am writting a kind of tutorial for mixing talib and pandas, are you interested in it? i would like to contribute to this verry usefull library.

I made some dataviz too, for example a graph with all kind of MA for a random numpy array but it is maybe more usefull for trading learning than for talib api learning... 

(excuse my english, i know it's bad)

**Comment by mrjbq7** [comment]
Glad you got it working! Appreciate any contributions you'd like to make. Thank you!  Your english is fine, and I'd be happy to help edit anything you put together if you'd like.
